### ISSUE TITLE
error KeyError: 'T116,T123' while running generate_datasets.py to preprocess 'MedMentions' data

### ISSUE THREAD

**Issue by dineshkh** [Raldir/Zero-shot-NERC#1]
I am getting error KeyError: 'T116,T123' while running generate_datasets.py to preprocess **MedMentions** data.
Below is command I ran.

`python generate_datasets.py --dataset medmentions --mode preprocess --input_path ./data/MedMentions --output_path /dccstor/dinesh/ZNER_baselines/formatted_data/corpus_pubtator.txt`

I have downloaded **MedMentions** data from [https://github.com/chanzuckerberg/MedMentions/tree/master/full/data](https://github.com/chanzuckerberg/MedMentions/tree/master/full/data
). 

The first mention in corpus_pubtator.txt is **25763772	0	5	DCTN4	T116,T123	C4308010** .

The error is because entity **DCTN4** is linked to two semantic types: "Amino Acid, Peptide, or Protein" (T116) and "Biologically Active Substance" (T123). The current code does not handle cases where an entity has more than one semantic types.

**Comment by Raldir** [comment]
Please use the st21pv subset: https://github.com/chanzuckerberg/MedMentions/tree/master/st21pv

**Comment by dineshkh** [comment]
Thanks
